-- 0008_webhook — the *push* transport that carries events outward (t142).
--
-- Closes extension point nº 5: `t123` delivered the *pull* half (the SSE
-- stream, which demands an open connection) and this one delivers the *push*
-- half, for whoever would rather receive a signed POST. Both read the SAME log
-- through the SAME function (`listEvents`), and neither touches the write path:
-- `recordEvent` does not know this file exists, and that is what makes a slow
-- or dead subscriber nobody's problem but its own.
--
-- Two tables, and the split between them is the usual one: what was CONTRACTED
-- and what HAPPENED.
--
-- `webhook_subscription` is the contract:
--
-- - `secret` is given by the caller, not generated by the server. There is no
--   show-once flow to build (`0007` has its own, for the credential), and
--   whoever subscribes normally already has a secret on their side. It goes in
--   as plain text because the signature is an HMAC: unlike `0007`'s credential,
--   which only needs to be COMPARED (and therefore becomes a digest), this key
--   needs to be REUSED on every delivery. No route reads this column back.
-- - `filter_types` is JSON and is nullable, and the two states differ: NULL is
--   "every type", `[]` is never written. The API validates the types against
--   the stream's own catalogue (`KNOWN_TYPES`) before writing, so what sits
--   here has already been through the taxonomy.
-- - `initial_event_id` is `MAX(event.id)` at the moment of creation, and it is
--   what prevents an accidental historical replay: a new subscription receives
--   whatever is written FROM HERE on, exactly like the stream with no
--   `Last-Event-ID`. Zero when the log is empty.
-- - `deactivated_at` is a date, not a flag — the same reason as `0007`'s
--   `revoked_at`: "when it stopped being valid" answers an audit question a
--   boolean erases. Nothing is deleted (D15/D2), and it is
--   `deactivated_at IS NULL` that separates a live subscription from a dead
--   one.
--
-- `webhook_delivery` is what happened, one row per (subscription, event):
--
-- - the `UNIQUE (subscription_id, event_id)` is what makes the fan-out
--   idempotent: it runs with `INSERT OR IGNORE`, so reprocessing the same
--   window — after a crash, after a restart, after a tick that died halfway —
--   duplicates no delivery at all. The same index serves the cursor's question
--   ("`MAX(event_id)` of this subscription"), which is where the fan-out
--   resumes from.
-- - the cursor is NOT a mutable column of the subscription: it is derived from
--   the deliveries already written. One column fewer is one state fewer to
--   disagree with what was actually queued.
-- - `status` has three values and two of them are terminal. `pending` is the
--   queue, `delivered` is the 2xx that arrived, `exhausted` is giving up —
--   whether by running past the last step of the backoff, or because the
--   subscription was deactivated with the delivery still in flight. The row is
--   erased in neither case: "I tried six times and gave up" is an audit fact.
-- - `next_attempt_at` is the queue's clock, and it is born equal to
--   `created_at`: a freshly queued delivery is due now. Each failure pushes
--   that date by the matching step of the backoff (10s, 1min, 5min, 30min, 2h).
--
-- No migration opens a transaction of its own: what transacts is src/db/migrate.ts.

CREATE TABLE webhook_subscription (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id        INTEGER NOT NULL,
  url               TEXT NOT NULL,
  secret            TEXT NOT NULL,          -- the HMAC key, given by whoever subscribes
  filter_types      TEXT,                   -- JSON with taxonomy types; NULL = every type
  initial_event_id  INTEGER NOT NULL,       -- MAX(event.id) at creation (0 if the log is empty)
  created_at        TEXT NOT NULL,
  deactivated_at    TEXT                    -- NULL = active, mirrors credential.revoked_at (0007)
);

-- The fan-out sweeps the live subscriptions on every tick, and it asks by
-- project.
CREATE INDEX idx_webhook_subscription_active ON webhook_subscription (deactivated_at, project_id);

CREATE TABLE webhook_delivery (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  subscription_id  INTEGER NOT NULL REFERENCES webhook_subscription(id),
  event_id         INTEGER NOT NULL REFERENCES event(id),
  status           TEXT NOT NULL CHECK (status IN ('pending','delivered','exhausted')),
  attempts         INTEGER NOT NULL DEFAULT 0,
  next_attempt_at  TEXT NOT NULL,
  created_at       TEXT NOT NULL,
  delivered_at     TEXT,
  last_error       TEXT,
  UNIQUE (subscription_id, event_id)        -- idempotent fan-out, and the cursor's index
);

-- The tick's hot question: "what is due right now?".
CREATE INDEX idx_webhook_delivery_pending ON webhook_delivery (status, next_attempt_at);
