-- 0009_sessao_transcricao — a saída crua da sessão, guardada para diagnóstico (t159).
--
-- Fecha o buraco nº 3 da primeira execução de verdade
-- (`notas/2026-08-15-first-execution.md`): "a perna 1 do refinar morreu com
-- exit 1 e trabalho quase pronto, e não há como diagnosticar: o prompt é
-- gravado, a saída não". A `0003` já guarda o `prompt` — o que ENTROU na
-- sessão — e nada guardava o que SAIU dela.
--
-- Três colunas aditivas em `session`, sem backfill: linha antiga lê `NULL`/`0`,
-- que é exatamente o que a API reporta com honestidade ("nenhuma transcrição
-- registrada"). Não há valor a inventar para uma sessão que terminou antes
-- desta migração existir.
--
-- - `transcript` é o texto cru que o engine imprimiu, as linhas do `onOutput`
--   juntadas por `\n`. Cru é requisito, não descuido: nem toda linha é um
--   frame estruturado, e "um CLI escreve seu grito de morte em texto puro no
--   meio do stream" (`packages/runner/src/engine/types.ts`, `SessionListener`).
--   Decodificar antes de gravar jogaria fora justamente a parte que interessa
--   quando a sessão morre.
-- - `transcricao_truncada` é 0/1, com teto de 1 MiB aplicado pelo servidor.
--   Quando estoura, o que fica é a CAUDA — o fim do stream é onde mora a
--   evidência de um crash — e a linha nunca cala sobre isso: o par
--   flag + tamanho original é o que separa "a sessão imprimiu 1 MiB" de "a
--   sessão imprimiu 40 MiB e você está lendo o último milésimo".
-- - `transcricao_tamanho_original` é o tamanho em BYTES antes do corte, e é
--   gravado sempre que há transcrição — igual ao tamanho do próprio texto
--   quando não houve truncagem. Bytes e não caracteres porque o teto é de
--   bytes; contar caracteres deixaria uma sessão em UTF-8 pesado passar do
--   teto sem que ninguém percebesse.
--
-- O que esta migração deliberadamente NÃO faz: mexer no envelope do evento.
-- `session.finished` continua carregando `status`/`exit_code`/`usage` e mais
-- nada (`especificacoes/eventos/schemas/session.finished.schema.json`
-- intocado). Transcrição é material de diagnóstico pendurado na projeção, não
-- fato de que estado de grafo dependa — duplicar um blob capado dentro de
-- `event.data` a cada sessão engorda o log append-only sem tornar nada mais
-- replayável. Quem quer a saída pergunta à sessão, do mesmo jeito que já
-- pergunta pelo `usage`, pelo `working_dir` e pelo `prompt`.
--
-- `transcricao_truncada` e `transcricao_tamanho_original` nascem em português e
-- ficam: a §4.2 do glossário registra `transcricao` -> `transcript` e não
-- registra nenhuma das duas, e a t235 não inventa vocabulário fora do
-- glossário. Fechá-las é acrescentar as linhas lá e uma migração curta — ficha
-- própria, como o cabeçalho da 0003 diz de `job.corpo`.
--
-- Nenhuma migração abre transação própria: quem transaciona é src/db/migrate.ts.

ALTER TABLE session ADD COLUMN transcript TEXT;                              -- NULO = nada foi reportado
ALTER TABLE session ADD COLUMN transcricao_truncada INTEGER NOT NULL DEFAULT 0; -- 0/1, teto de 1 MiB
ALTER TABLE session ADD COLUMN transcricao_tamanho_original INTEGER;         -- bytes ANTES do corte
