-- 0009_sessao_transcricao — the session's raw output, kept for diagnosis (t159).
--
-- Closes hole nº 3 of the first real execution
-- (`notes/2026-08-15-first-execution.md`): "leg 1 of the refine node died with
-- exit 1 and the work nearly done, and there is no way to diagnose it: the
-- prompt is recorded, the output is not". `0003` already keeps the `prompt` —
-- what went INTO the session — and nothing kept what came OUT of it.
--
-- Three additive columns on `session`, with no backfill: an old row reads
-- `NULL`/`0`, which is exactly what the API reports honestly ("no transcript
-- recorded"). There is no value to invent for a session that ended before this
-- migration existed.
--
-- - `transcript` is the raw text the engine printed, the `onOutput` lines
--   joined by `\n`. Raw is a requirement, not carelessness: not every line is a
--   structured frame, and "a CLI writes its dying scream in plain text in the
--   middle of the stream" (`packages/runner/src/engine/types.ts`,
--   `SessionListener`). Decoding before writing would throw away precisely the
--   part that matters when the session dies.
-- - `transcricao_truncada` is 0/1, with a 1 MiB ceiling applied by the server.
--   When it overflows, what survives is the TAIL — the end of the stream is
--   where the evidence of a crash lives — and the row never keeps quiet about
--   it: the flag + original size pair is what separates "the session printed
--   1 MiB" from "the session printed 40 MiB and you are reading the last
--   thousandth of it".
-- - `transcricao_tamanho_original` is the size in BYTES before the cut, and it
--   is written whenever there is a transcript — equal to the size of the text
--   itself when nothing was truncated. Bytes and not characters because the
--   ceiling is in bytes; counting characters would let a session in heavy UTF-8
--   run past the ceiling with nobody noticing.
--
-- What this migration deliberately does NOT do: touch the event envelope.
-- `session.finished` still carries `status`/`exit_code`/`usage` and nothing
-- else (`specs/events/schemas/session.finished.schema.json` untouched). A
-- transcript is diagnostic material hanging off the projection, not a fact any
-- graph state depends on — duplicating a capped blob inside `event.data` on
-- every session fattens the append-only log without making anything more
-- replayable. Whoever wants the output asks the session, the same way they
-- already ask it for `usage`, for `working_dir` and for `prompt`.
--
-- `transcricao_truncada` and `transcricao_tamanho_original` are born in
-- Portuguese and stay: §4.2 of the glossary records `transcricao` -> `transcript`
-- and records neither of these two, and t235 does not invent vocabulary outside
-- the glossary. Closing them means adding those rows there plus a short
-- migration — a ticket of its own, as 0003's header says of `job.corpo`.
--
-- No migration opens a transaction of its own: what transacts is src/db/migrate.ts.

ALTER TABLE session ADD COLUMN transcript TEXT;                              -- NULL = nothing was reported
ALTER TABLE session ADD COLUMN transcricao_truncada INTEGER NOT NULL DEFAULT 0; -- 0/1, 1 MiB ceiling
ALTER TABLE session ADD COLUMN transcricao_tamanho_original INTEGER;         -- bytes BEFORE the cut
