-- 0010_sessao_orcamento_silencio — the session's second budget, and the cause of
-- the stop (t163).
--
-- Until now the session had a single watchdog: `timeout_seconds`, a wall clock,
-- armed when it opened. A stuck session with the process still standing ran the
-- whole budget — an hour, on the dispatch default — with nothing ever asking
-- "is this still producing anything?". The two columns below are the other axis
-- and the trace it leaves behind.
--
-- - `silence_seconds` is the INACTIVITY ceiling the session was opened with, in
--   seconds, and it is independent of `timeout_seconds` on purpose: the two
--   measure different things. The clock answers "this has cost too much
--   already"; the silence answers "this stopped happening". A session can stay
--   alive and productive for an hour, and another can hang in two minutes with
--   the process still standing — and only the second axis sees the second one.
-- - `timeout_reason` is which of the two bit: `wall_clock` or `silence`. It is
--   `CHECK`ed because a third value here is not new data, it is a mistake by
--   whoever wrote it — and the projection is read by a person deciding whether
--   to investigate.
--
-- **Why the cause is a field and not a status.** `session.finished.status`
-- still has the six values it had: both of our stops end up in `timed_out`,
-- told apart by this column. Growing the status vocabulary was rejected once,
-- for quota states, with the reasoning that holds just as well here — "the real
-- reason lives in the event log, which is append-only and loses nothing"
-- (`docs/formats/engine-adapter.md`, *Rejected — a richer `SessionStatus`*).
-- And `stuck`, which the taxonomy described as "stopped by silence", never was
-- that in practice: it is the slot for whoever has no slot
-- (`pending`/`running`/`cancelled`). The prose was corrected alongside this
-- ticket.
--
-- Both columns are nullable and without backfill, as `timeout_seconds` already
-- was: a row older than this migration reads `NULL`/`NULL`, which is exactly
-- what it is — "declared no policy" and "does not apply". There is no value to
-- invent for a session that ended before the second watchdog existed.
--
-- Both VALUES of `timeout_reason` were born in English, being vocabulary of the
-- EngineAdapter interface, which is English throughout and is what produces
-- them — and that is why t235, which took the rest of the schema's
-- CHECK-pinned values to English, had nothing to do in this migration.
--
-- No migration opens a transaction of its own: what transacts is src/db/migrate.ts.

ALTER TABLE session ADD COLUMN silence_seconds INTEGER;  -- NULL = no policy of its own
ALTER TABLE session ADD COLUMN timeout_reason  TEXT
  CHECK (timeout_reason IN ('wall_clock', 'silence'));  -- NULL = no watchdog bit
