-- 0013_trabalho_campos_customizados — os campos que a CLASSE declara na ficha (t168).
--
-- Renumerada de 0012 para 0013: a 0012_motor_modelo (t166) chegou antes na
-- branch, e `src/db/migrate.ts` falha alto em número repetido. Nenhuma ordem de
-- dependência entre as duas — esta só mexe em `trabalho`.
--
-- A classe de bets assimétricas (D14) precisa de `downside`, `upside` e
-- `premise_source` na ficha; desenvolvimento de software não precisa de nenhum
-- deles. Uma coluna por campo seria uma migração por classe de problema, e é
-- por isso que a DEFINIÇÃO mora no documento de grafo da classe
-- (`custom_fields`, schema/grafo.schema.json) e só o VALOR mora aqui.
--
-- `campos` é JSON em coluna TEXT, como `criterios_de_aceite` ao lado e como
-- `sessao.uso`, `pergunta.opcoes` e `intake_rascunho.itens`: as chaves são
-- declaradas pela classe, então normalizar em tabela obrigaria o control plane
-- a conhecer o vocabulário de cada classe — exatamente o que a D8 tira dele.
--
-- NULO e `{}` são coisas diferentes, a mesma disciplina que `corpo` e
-- `criterios_de_aceite` seguem desde a 0006: NULO é "esta ficha nasceu sem
-- campo nenhum", `{}` é "a classe declara campos e ninguém preencheu ainda".
--
-- Quem cobra um campo obrigatório é a rota de transição, em código
-- (`custom_fields[].required_at` × `no_atual`), e não um CHECK aqui: o que é
-- exigido muda com a VERSÃO DE GRAFO do trabalho, e um CHECK de tabela não sabe
-- em que nó a ficha está nem sob qual versão ela corre.
--
-- Nenhuma migração abre transação própria: quem transaciona é src/db/migrate.ts.

ALTER TABLE trabalho ADD COLUMN campos TEXT; -- JSON: {[nome]: string|number|boolean}; NULL != {}
