-- 0013_sessao_modelos — which models ran the session (t172).
--
-- Until now the log could say which ENGINE ran each session
-- (`session.opened.engine`, since t102) and never which model. "Cost per model"
-- had no answer, not because aggregation was missing, but because the datum was
-- never collected: there was no field for it anywhere — not in the taxonomy,
-- not in the table, not in the EngineAdapter interface.
--
-- - `models` is a JSON array of identifiers, on the same storage convention as
--   `criterios_de_aceite` in `job`: TEXT with JSON inside, projected back into a
--   list by the repository. NULL is "the engine named none", and an empty list
--   is not a valid answer — what says "nothing" is the NULL.
-- - **A list, and not a single identifier.** A session runs more than one
--   model, and that was measured, not assumed: a single turn of the real CLI
--   returned two of them in the terminal frame's `modelUsage` — the main turn's
--   and that of a cheaper auxiliary. Collapsing to "the" model would put the
--   whole bill on the wrong one, which is the same damage the "absence is never
--   zero" rule avoids for tokens.
-- - **No `CHECK`, unlike `timeout_reason` in 0011.** There the value set is
--   closed and comes from our own interface, so a third value is a mistake by
--   whoever wrote it. Here the set is open by nature: the value is the
--   identifier the engine reported, and a migration per new model would be the
--   same closed enum 0012 already refused for `engine_model.model_id`.
--
-- Nullable and without backfill, like `silence_seconds`, `timeout_reason` and
-- `transcript` before it: a row older than this migration reads NULL, which is
-- exactly what it is. There is no value to invent for a session that ended
-- before anybody was counting — and inventing one would be writing into the log
-- a fact nobody measured.
--
-- The VALUES are the engine's strings, and they arrive as the engine wrote
-- them: there is no enum here for t235 to translate.
--
-- No migration opens a transaction of its own: what transacts is src/db/migrate.ts.

ALTER TABLE session ADD COLUMN models TEXT;  -- NULL = the engine named no model
