-- 0014_pergunta_no_id — which node the question came from (t167).
--
-- Renumbered from 0013 to 0014 (t187): three tickets in parallel asked for the
-- same 0013 at integration, and `src/db/migrate.ts` fails loudly on a repeated
-- number. 0013 went to `0013_sessao_modelos` (t172). No dependency order
-- between them — this one only touches `input_request`.
--
-- Until now a question knew which JOB it belonged to, and which execution, but
-- not which NODE: `input_request` carried `job_id` and `execution_id`, and the
-- job's position lived only in the timeline, mixed in with every transition
-- that came afterwards. Whoever wanted to answer "which nodes stop most often
-- to ask for a person?" had to rebuild the traversal event by event and hope no
-- transition had happened between the question and the reading.
--
-- The escalation policy becomes node data in this same ticket, and that is what
-- makes the column necessary rather than merely convenient: a per-node policy
-- nobody can cross with that node's questions is a policy nobody can evaluate.
-- The per-node count (the execution route) and any future auto-answer gate read
-- from here.
--
-- **What writes it is the server, from the owning job's `current_node_id`** —
-- never the request body, the same trust boundary `project_id` and
-- `execution_id` already have. A question that declared its own node would be a
-- question able to lie about where the job was.
--
-- Nullable and without backfill, as `session.engine_session_ref` already is: a
-- row older than this migration reads `NULL`, which is exactly what it is —
-- "which node it came from is not known". There is no value to invent for a
-- question asked before the column existed, and the job's entry node would be
-- precisely the guess the column exists to make unnecessary.
--
-- `node_id` is the same name `session.node_id` already uses for the same fact:
-- one row in §4.2 of the glossary, one name across both tables.
--
-- No migration opens a transaction of its own: what transacts is src/db/migrate.ts.

ALTER TABLE input_request ADD COLUMN node_id TEXT;  -- NULL = which node it came from is unknown
