-- 0014_pergunta_no_id — de qual nó veio a pergunta (t167).
--
-- Renumerada de 0013 para 0014 (t187): três tickets em paralelo pediram o mesmo
-- 0013 na integração, e `src/db/migrate.ts` falha alto em número repetido. A
-- 0013 ficou com a `0013_sessao_modelos` (t172). Nenhuma ordem de dependência
-- entre elas — esta só mexe em `input_request`.
--
-- Até aqui uma pergunta sabia de qual TRABALHO ela era, e de qual execução, mas
-- não de qual NÓ: `input_request` carregava `job_id` e `execution_id`, e a
-- posição do trabalho ficava só na linha do tempo, misturada com todas as
-- transições que vieram depois. Quem quisesse responder "quais nós mais param
-- pedindo gente?" tinha de reconstruir a travessia evento a evento e torcer
-- para nenhuma transição ter acontecido entre a pergunta e a leitura.
--
-- A política de escalação passa a ser dado do nó nesta mesma ficha, e é isso
-- que torna a coluna necessária e não apenas conveniente: uma política por nó
-- que ninguém consegue cruzar com as perguntas daquele nó é uma política que
-- ninguém consegue avaliar. A contagem por nó (a rota de execução) e qualquer
-- portão futuro de auto-resposta leem daqui.
--
-- **Quem escreve é o servidor, a partir do `current_node_id` do trabalho dono** —
-- nunca o corpo da requisição, a mesma fronteira de confiança que `project_id` e
-- `execution_id` já têm. Uma pergunta que declarasse o próprio nó seria uma
-- pergunta capaz de mentir sobre onde o trabalho estava.
--
-- Anulável e sem backfill, como `session.engine_session_ref` já é: linha
-- anterior a esta migração lê `NULL`, que é exatamente o que ela é — "não se
-- sabe de qual nó veio". Não há valor a inventar para uma pergunta feita antes
-- de a coluna existir, e o nó de entrada do trabalho seria justamente o palpite
-- que a coluna existe para não precisar dar.
--
-- `node_id` é o mesmo nome que `session.node_id` já usa para o mesmo fato: uma
-- linha só na §4.2 do glossário, um nome só nas duas tabelas.
--
-- Nenhuma migração abre transação própria: quem transaciona é src/db/migrate.ts.

ALTER TABLE input_request ADD COLUMN node_id TEXT;  -- NULO = não se sabe de qual nó veio
