-- 0015_trabalho_campos_customizados — the fields the CLASS declares on the ticket (t168).
--
-- Renumbered twice, from 0012 to 0013 and from 0013 to 0015 (t187):
-- 0012_motor_modelo (t166) reached the branch first, and the 0013 that followed
-- was claimed in parallel by two more tickets — it went to
-- `0013_sessao_modelos` (t172), and `0014_pergunta_no_id` (t167) came after.
-- `src/db/migrate.ts` fails loudly on a repeated number. No dependency order
-- between them — this one only touches `job`.
--
-- The asymmetric-bets class (D14) needs `downside`, `upside` and
-- `premise_source` on the ticket; software development needs none of them. One
-- column per field would be one migration per problem class, and that is why
-- the DEFINITION lives in the class's graph document (`custom_fields`,
-- schema/graph.schema.json) and only the VALUE lives here.
--
-- `fields` is JSON in a TEXT column, like `criterios_de_aceite` beside it and
-- like `session.usage`, `input_request.options` and `intake_draft.items`: the
-- keys are declared by the class, so normalizing them into a table would force
-- the control plane to know every class's vocabulary — exactly what D8 takes
-- away from it.
--
-- NULL and `{}` are different things, the same discipline `corpo` and
-- `criterios_de_aceite` have followed since 0006: NULL is "this ticket was born
-- with no field at all", `{}` is "the class declares fields and nobody has
-- filled one in yet".
--
-- What demands a mandatory field is the transition route, in code
-- (`custom_fields[].required_at` × `current_node_id`), and not a CHECK here:
-- what is demanded changes with the job's GRAPH VERSION, and a table CHECK
-- knows neither which node the ticket sits on nor which version it runs under.
--
-- No migration opens a transaction of its own: what transacts is src/db/migrate.ts.

ALTER TABLE job ADD COLUMN fields TEXT; -- JSON: {[name]: string|number|boolean}; NULL != {}
