-- 0017_trabalho_tier — what this job costs to run (t175).
--
-- Renumbered from 0012 to 0017 (the ticket asked for 0012, and the ticket was
-- written before 0012_motor_modelo, 0013_sessao_modelos, 0014_pergunta_no_id,
-- 0015_trabalho_campos_customizados and 0016_gancho reached main). It is the
-- third time this happens — 0015 tells its own story — and
-- `src/db/migrate.ts` fails loudly on a repeated number. No dependency order:
-- this one only touches `job`.
--
-- The concept is not new in the repository, it is DEFERRED in two places:
-- `docs/spec/graph.md:401-403` left flowpilot's `work_tier` out of the ported
-- graph, and `docs/spec/topografo-cost.md` recorded that neither the graph
-- document nor the skill manifest has a cost or tier field. This column is the
-- narrowest possible slice of that debt, and the boundary is what keeps it
-- narrow: `tier` changes how much a node COSTS to run, never which edge the job
-- leaves by. The graph stays frozen during execution (principle 2), and the
-- only in-flight decisions are still the gate verdicts.
--
-- **A closed `CHECK`, unlike `session.models` and `engine_model`.** There the
-- set is open by nature — the value is an identifier the engine reported, and
-- an enum would force a migration per new model. Here the set is ours:
-- `trivial` and `standard` are this triage's own vocabulary, and a third value
-- is not new data, it is a mistake by whoever wrote it. The same reasoning as
-- `timeout_reason` in 0011 and `source` in 0012.
--
-- **NULL is not `trivial`.** It is this column's one dangerous reading, and
-- that is why it is nullable and without backfill, like `silence_seconds`,
-- `transcript` and `fields` before it: a row older than this migration reads
-- NULL, which is exactly what it is — nobody triaged. Collapsing absence into
-- "trivial" would demote to a cheaper model every job that existed before this
-- ticket, with nobody having chosen that and with nothing failing anywhere.
--
-- There is no MODEL column here, and the absence is deliberate: which model is
-- the cheap one is engine vocabulary, and it lives below the `EngineAdapter`'s
-- boundary 1, inside each adapter. The control plane keeps the classification;
-- what translates it into `--model` is whoever knows what a model is.
--
-- Both VALUES were born in English, being vocabulary of the EngineAdapter
-- interface, which is English throughout and is what consumes them — the same
-- reasoning 0011 wrote down for `wall_clock` and `silence`.
--
-- No migration opens a transaction of its own: what transacts is src/db/migrate.ts.

ALTER TABLE job ADD COLUMN tier TEXT  -- NULL = nobody triaged; NULL != 'trivial'
  CHECK (tier IS NULL OR tier IN ('trivial', 'standard'));
