-- 0020_sessao_saida — o resultado estruturado que a sessão relata do nó (t253).
--
-- É a metade que ESCREVE da projeção de input por nó. Até aqui nenhum evento e
-- nenhuma tabela carregava a saída estruturada de um nó, então nada tinha como
-- montar o objeto que a `input` do nó seguinte declara: o despacho passava `{}`
-- e toda skill com placeholder recusava em produção
-- (`packages/runner/src/dispatch/options.ts`, `resolveInput`). Esta coluna é o
-- lugar onde o `merge_commit` que `implantar` lê passa a existir depois que
-- `integrar` o produziu.
--
-- - `output` é JSON num TEXT, mesma convenção de `usage`, `models` e
--   `criterios_de_aceite`: objeto na entrada, objeto na projeção, e o
--   repositório é quem serializa. Não é uma coluna por chave porque as chaves
--   são da CLASSE — o `output_schema` da skill pinada pelo nó é quem as declara
--   (D9) —, e uma coluna por chave seria uma migração por classe de problema.
-- - **Sem `CHECK`, e sem conferência aqui.** O que a forma de dentro tem que ser
--   é decidido contra o schema da própria skill, no `PATCH /finish`, onde a
--   linha do registro está ao alcance. O banco guarda; quem julga é o control
--   plane, que é o único que escreve (D1).
-- - **NULO é "nada estruturado foi relatado", e nunca `{}`.** As duas leituras
--   são fatos diferentes: objeto vazio é uma sessão que relatou um objeto sem
--   chave nenhuma, NULO é uma sessão que não relatou. É a mesma disciplina que
--   `usage` tem desde a t102 e `transcript` desde a t159 — e é também o que a
--   linha grava quando o relato não casou com o schema, com o motivo indo para
--   `output_schema_error` no evento em vez de para cá.
--
-- Anulável e sem backfill, como `silence_seconds`, `models`, `transcript` e
-- `tier` antes dela: linha anterior a esta migração lê NULO, que é exatamente o
-- que ela é. Não há valor a inventar para uma sessão que terminou antes de
-- alguém estar coletando, e inventar um seria escrever no banco um fato que
-- ninguém mediu.
--
-- O nome da coluna já nasce em inglês, como todo o resto da tabela desde o
-- quarto filho da D20 (t229); `Session.saida` é a projeção interna, e o `SELECT`
-- do repositório é quem faz o apelido.
--
-- Nenhuma migração abre transação própria: quem transaciona é src/db/migrate.ts.

ALTER TABLE session ADD COLUMN output TEXT;  -- NULO = nada estruturado foi relatado
