-- 0020_sessao_saida — the structured result the session reports from the node (t253).
--
-- It is the WRITING half of the per-node input projection. Until now no event
-- and no table carried a node's structured output, so nothing could assemble
-- the object the next node's `input` declares: dispatch passed `{}` and every
-- skill with a placeholder refused in production
-- (`packages/runner/src/dispatch/options.ts`, `resolveInput`). This column is
-- where the `merge_commit` that `implantar` reads starts existing after
-- `integrar` has produced it.
--
-- - `output` is JSON in a TEXT, the same convention as `usage`, `models` and
--   `criterios_de_aceite`: an object on the way in, an object in the
--   projection, and the repository is what serializes. It is not one column per
--   key because the keys belong to the CLASS — the `output_schema` of the skill
--   the node pins is what declares them (D9) — and one column per key would be
--   one migration per problem class.
-- - **No `CHECK`, and no checking here.** What the shape inside has to be is
--   decided against the skill's own schema, in `PATCH /finish`, where the
--   registry row is within reach. The database keeps; what judges is the
--   control plane, which is the only writer (D1).
-- - **NULL is "nothing structured was reported", and never `{}`.** The two
--   readings are different facts: an empty object is a session that reported an
--   object with no key at all, NULL is a session that reported nothing. It is
--   the same discipline `usage` has had since t102 and `transcript` since t159
--   — and it is also what the row records when the report did not match the
--   schema, with the reason going to `output_schema_error` on the event rather
--   than here.
--
-- Nullable and without backfill, like `silence_seconds`, `models`, `transcript`
-- and `tier` before it: a row older than this migration reads NULL, which is
-- exactly what it is. There is no value to invent for a session that ended
-- before anybody was collecting, and inventing one would be writing into the
-- database a fact nobody measured.
--
-- The column's name is born in English, like all the rest of the table since
-- D20's fourth child (t229); `Session.saida` is the internal projection, and
-- the repository's `SELECT` is what does the aliasing.
--
-- No migration opens a transaction of its own: what transacts is src/db/migrate.ts.

ALTER TABLE session ADD COLUMN output TEXT;  -- NULL = nothing structured was reported
