-- 0023_schema_migrations_checksum — a content checksum per applied migration
-- (t279, notes/2026-08-18-action-plan.md §2).
--
-- The ledger only knew WHETHER an id had run, never WHAT ran. D20 rewrote
-- nineteen migrations IN PLACE — same file, same id, translated content — and
-- in a database that already had them recorded the runner skips them all in
-- silence: the server comes up clean and dies later, in the middle of a
-- request, with a `no such column` for a name that only exists in the new
-- schema. This column is what turns that silence into a failure at startup,
-- with a first and a last name.
--
-- Nullable on purpose: the row of a migration applied before this column
-- existed has no way of knowing retroactively what the file looked like when it
-- ran. The runner (src/db/migrate.ts) back-fills those from the current file,
-- once, with a warning — it is a best-effort record, not a verified one. A row
-- inserted from this migration onwards always carries a real checksum.
--
-- One self-reference detail the runner has to handle and this migration does
-- not: in a new database, 0001 through 0022 write their rows BEFORE the column
-- exists, inside the SAME `migrate()` call. That is why the INSERT asks
-- (`PRAGMA table_info`) whether the column already exists in this transaction,
-- and whatever is left NULL is filled in on the next pass, in silence — nothing
-- had a chance to diverge inside a single process.
--
-- No migration opens a transaction of its own: what transacts is src/db/migrate.ts.

ALTER TABLE schema_migrations ADD COLUMN checksum TEXT;  -- NULL = applied before this migration existed
